services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memoria_backend
    env_file:
      - ./backend/.env
    ports:
      - "28080:28080"
    volumes:
      - ./backend/templates:/app/templates:ro
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_ADMIN_BASE_URL: http://localhost:23002
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:23001
    container_name: memoria_frontend
    env_file:
      - ./frontend/.env
    environment:
      PORT: 23000
    ports:
      - "23000:23000"
    depends_on:
      - backend

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_APP_BASE_URL: http://localhost:23000
        NEXT_PUBLIC_ADMIN_BASE_URL: http://localhost:23002
        NEXT_PUBLIC_INFO_BASE_URL: http://localhost:23004
        NEXT_PUBLIC_HELP_BASE_URL: http://localhost:23003
        NEXT_PUBLIC_APP_ENV: development
    container_name: memoria_auth
    env_file:
      - ./auth/.env
    environment:
      PORT: 23001
    ports:
      - "23001:23001"
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_APP_BASE_URL: http://localhost:23000
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:23001
    container_name: memoria_admin
    env_file:
      - ./admin/.env
    environment:
      PORT: 23002
    ports:
      - "23002:23002"
    depends_on:
      - backend

  help:
    build:
      context: ./help
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:23001
    container_name: memoria_help
    env_file:
      - ./help/.env
    environment:
      PORT: 23003
    ports:
      - "23003:23003"
    depends_on:
      - backend

  info:
    build:
      context: ./info
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:23001
        NEXT_PUBLIC_CONTACT_BASE_URL: http://localhost:23005
    container_name: memoria_info
    env_file:
      - ./info/.env
    environment:
      PORT: 23004
    ports:
      - "23004:23004"
    depends_on:
      - backend

  contact:
    build:
      context: ./contact
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:28080
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:23001
        NEXT_PUBLIC_INFO_BASE_URL: http://localhost:23004
    container_name: memoria_contact
    env_file:
      - ./contact/.env
    environment:
      PORT: 23005
    ports:
      - "23005:23005"
    depends_on:
      - backend
